package GUI;

import data.Consola;
import data.Producto;
import data.Tienda;
import data.Videojuego;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author alber
 */
public class PListados extends javax.swing.JPanel {

    /**
     * Creates new form PListados
     */
    Tienda tienda;
    VPal v;
    public PListados(VPal v, Tienda tienda) {
        this.v = v;
        this.tienda = tienda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaListado = new javax.swing.JTextArea();
        panelInferior = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        botonListadoNormal = new javax.swing.JButton();
        botonListadoConsolas = new javax.swing.JButton();
        botonListadoJuegos = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.GridLayout(2, 1));

        areaListado.setColumns(20);
        areaListado.setRows(5);
        jScrollPane1.setViewportView(areaListado);

        add(jScrollPane1);

        panelInferior.setLayout(new java.awt.GridLayout(2, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelInferior.add(jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelInferior.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelInferior.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelInferior.add(jPanel6);

        botonListadoNormal.setText("Listado Total");
        botonListadoNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoNormalActionPerformed(evt);
            }
        });
        panelInferior.add(botonListadoNormal);

        botonListadoConsolas.setText("Listado Consolas");
        botonListadoConsolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoConsolasActionPerformed(evt);
            }
        });
        panelInferior.add(botonListadoConsolas);

        botonListadoJuegos.setText("Listado Juegos");
        botonListadoJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoJuegosActionPerformed(evt);
            }
        });
        panelInferior.add(botonListadoJuegos);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        panelInferior.add(botonVolver);

        add(panelInferior);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.areaListado.setText("");
        v.setContentPane(v.ppal);
        v.revalidate();

    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonListadoNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoNormalActionPerformed
        this.areaListado.setText(tienda.toString());
    }//GEN-LAST:event_botonListadoNormalActionPerformed

    private void botonListadoConsolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoConsolasActionPerformed
        this.areaListado.setText(generarListadoFiltrado(Consola.class, "Consolas de la tienda ordenadas por precio: \n"));
    }//GEN-LAST:event_botonListadoConsolasActionPerformed

    private void botonListadoJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoJuegosActionPerformed
        this.areaListado.setText(generarListadoFiltrado(Videojuego.class,"Videojuegos de la tienda ordenados por precio \n"));
    }//GEN-LAST:event_botonListadoJuegosActionPerformed
    
    private String generarListadoFiltrado(Class<?> tipo, String titulo){
        List<Producto> productosOrdenados = new ArrayList<>(v.tienda.getProductos());
        productosOrdenados.sort(Comparator.comparingDouble(Producto::getPrecio));
       
        StringBuilder resultado = new StringBuilder("Juegos de la tienda ordenados por precio: \n");
        for (Producto p : productosOrdenados) {
            if(tipo.isInstance(p))
            resultado.append(p.toString()).append("\n");
        }
        return resultado.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaListado;
    private javax.swing.JButton botonListadoConsolas;
    private javax.swing.JButton botonListadoJuegos;
    private javax.swing.JButton botonListadoNormal;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInferior;
    // End of variables declaration//GEN-END:variables
}
